name: build-sphinx-to-gh-pages
description: Build Sphinx to GitHub Pages
on: 
  push:
    branches: [ main ]
jobs:
  build_sphinx_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: $GITHUB_ACTION_PATH/buildsite.sh
        shell: bash

